a = float(input('Введите цену: '))
b = float(input('Введите цену: '))
c = float(input('Введите цену: '))
d = float(input('Введите цену: '))
e = float(input('Введите цену: '))
a = round(a, 0)
print(a)
b = round(b, 0)
print(b)
c = round(c, 0)
print(c)
d = round(d, 0)
print(d)
e = round(e, 0)
print(e)
